# Generated by Django 5.1.2 on 2024-10-25 08:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Dept_name', models.CharField(max_length=50)),
                ('Dept_D_no', models.IntegerField()),
                ('Dept_head', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Reg_no', models.CharField(max_length=50)),
                ('D_name', models.CharField(max_length=50)),
                ('D_phone', models.CharField(max_length=50)),
                ('D_qualification', models.CharField(max_length=50)),
                ('D_specialisation', models.CharField(max_length=50)),
                ('D_Department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.patient')),
            ],
        ),
    ]
