# Generated by Django 5.1.2 on 2024-10-26 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_alter_department_dept_name_alter_doctor_d_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='D_Avl_Day',
            field=models.DateTimeField(default='None'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='patient',
            name='age',
            field=models.IntegerField(),
        ),
    ]
