# Generated by Django 5.1.2 on 2024-10-26 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_doctor_d_avl_day_alter_patient_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='D_Avl_Day',
            field=models.CharField(max_length=50),
        ),
    ]
